/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.GuedesDesenvolvimento.SistemaSGC.Apresentacao;

import br.GuedesDesenvolvimento.SistemaSGC.Entidade.Produto;
import br.GuedesDesenvolvimento.SistemaSGC.Negocio.ProdutoBO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Igor
 */
public class TelaExibirProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaExibirProdutos
     */
    private List<Produto> produtos;

    public TelaExibirProdutos() throws SQLException {
        initComponents();
        produtos = new ArrayList<Produto>();
        ExibirDadosTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlExibirClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutosCadastrados = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos Cadastrados");
        setAlwaysOnTop(true);
        setExtendedState(6);

        pnlExibirClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Cadastrados"));

        tblProdutosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tblProdutosCadastrados);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExibirClientesLayout = new javax.swing.GroupLayout(pnlExibirClientes);
        pnlExibirClientes.setLayout(pnlExibirClientesLayout);
        pnlExibirClientesLayout.setHorizontalGroup(
            pnlExibirClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExibirClientesLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(42, 42, 42)
                .addComponent(btnVoltar)
                .addGap(24, 24, 24))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlExibirClientesLayout.setVerticalGroup(
            pnlExibirClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExibirClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlExibirClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExibirClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExibirClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int linhaSelecionada = tblProdutosCadastrados.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Nenhum produto selecionado!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }else{
            Produto produtoSelecionado =produtos.get(linhaSelecionada);
            TelaEditarProduto telaEditarProduto= new TelaEditarProduto(produtoSelecionado);
            telaEditarProduto.setVisible(true);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSelecionada= tblProdutosCadastrados.getSelectedRow();
        Produto produtoSelecionado=produtos.get(linhaSelecionada);
               
        String mensagem="Deseja excluir? "+produtoSelecionado.getNome();
        String titulo="Excluir";
        int resultado= JOptionPane.showConfirmDialog(this, mensagem, titulo, JOptionPane.YES_NO_OPTION); 
        if(resultado==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Sim");
        }else if(resultado==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, "Não");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed
    public void ExibirDadosTabela() throws SQLException {
        try {
            carregarListaProdutos();
            ModelosTabelaProdutos modelosTabelaProdutos = new ModelosTabelaProdutos();
            tblProdutosCadastrados.setModel(modelosTabelaProdutos);
        } catch (Exception e) {
            exibirMensagemErro();
            e.printStackTrace();
        }
    }

    private void exibirMensagemErro() {
        String titulo = "Erro!";
        String mensagem = "Erro ao carregar Produtos!";
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }

    public void carregarListaProdutos() throws SQLException {
        ProdutoBO produtoBO = new ProdutoBO();
        this.produtos = produtoBO.buscarProdutos();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaExibirProdutos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaExibirProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    class ModelosTabelaProdutos extends AbstractTableModel {

        @Override
        public String getColumnName(int Column) {
            if (Column == 0) {
                return "Codigo";
            } else if (Column == 1) {
                return "Nome";
            } else if (Column == 2) {
                return "Preco";
            } else {
                return "Quantidade";
            }

        }

        @Override
        public int getRowCount() {
            return produtos.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int linha, int coluna) {

            Produto produto = produtos.get(linha);
            if (coluna == 0) {
                return produto.getCodigo();
            } else if (coluna == 1) {
                return produto.getNome();
            } else if (coluna == 2) {
                return produto.getPreco();
            } else {
                return produto.getQuantidade();
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlExibirClientes;
    private javax.swing.JTable tblProdutosCadastrados;
    // End of variables declaration//GEN-END:variables
}
