/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.GuedesDesenvolvimento.SistemaSGC.Apresentacao;

/**
 *
 * @author Igor
 */
public class TelaNovoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaNovoUsuario
     */
    public TelaNovoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        mnuCadastroUsuários = new javax.swing.JMenuBar();
        mnuCadastroUsuarios = new javax.swing.JMenu();
        mnuNovoUsuario = new javax.swing.JMenuItem();
        mnuAlterar = new javax.swing.JMenuItem();
        mnuExibir = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar usuários");
        setExtendedState(6);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        mnuCadastroUsuarios.setText("Menu");

        mnuNovoUsuario.setText("Novo");
        mnuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoUsuarioActionPerformed(evt);
            }
        });
        mnuCadastroUsuarios.add(mnuNovoUsuario);

        mnuAlterar.setText("Alterar");
        mnuCadastroUsuarios.add(mnuAlterar);

        mnuExibir.setText("Exibir");
        mnuExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExibirActionPerformed(evt);
            }
        });
        mnuCadastroUsuarios.add(mnuExibir);

        mnuExcluir.setText("Excluir");
        mnuCadastroUsuarios.add(mnuExcluir);

        mnuCadastroUsuários.add(mnuCadastroUsuarios);
        mnuCadastroUsuários.add(jMenu2);

        setJMenuBar(mnuCadastroUsuários);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoUsuarioActionPerformed
        TelaCadastrarUsuario telaCadastrarUsuario = new TelaCadastrarUsuario();
        telaCadastrarUsuario.setVisible(true);
    }//GEN-LAST:event_mnuNovoUsuarioActionPerformed

    private void mnuExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExibirActionPerformed
        TelaExibirUsuarios telaExibirUsuarios = new TelaExibirUsuarios();
        telaExibirUsuarios.setVisible(true);
        
    }//GEN-LAST:event_mnuExibirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem mnuAlterar;
    private javax.swing.JMenu mnuCadastroUsuarios;
    private javax.swing.JMenuBar mnuCadastroUsuários;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JMenuItem mnuExibir;
    private javax.swing.JMenuItem mnuNovoUsuario;
    // End of variables declaration//GEN-END:variables
}
